# Generated by Django 5.1.6 on 2025-02-12 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=250)),
                ("author", models.CharField(db_index=True, max_length=250)),
                (
                    "isbn",
                    models.CharField(db_index=True, max_length=13, verbose_name="ISBN"),
                ),
                (
                    "pages",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Book is available"
                    ),
                ),
            ],
            options={
                "verbose_name": "book",
                "verbose_name_plural": "books",
            },
        ),
    ]
